const resList=[ 
   {
   "info": {
   "id": "322324","name": "Biryani Blues","cloudinaryImageId": "97377e54937c079fe269d744aa66274a","locality": "Sarfabad","areaName": "Sector 72","costForTwo": "₹400 for two","cuisines": ["Biryani","Hyderabadi","Lucknowi","Kebabs","Desserts","Beverages"],"avgRating": 4.4,"parentId": "13813","avgRatingString": "4.4","totalRatingsString": "10K+","sla": {"deliveryTime": 28,"lastMileTravel": 4.8,"serviceability": "SERVICEABLE","slaString": "25-30 mins","lastMileTravelString": "4.8 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-27 04:00:00","opened": true},"badges": {},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹69"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}},
   {
"info": {
      "id": "253735","name": "McDonald's","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/9/d4b98c24-5546-4031-86f7-8cd6be9ebc01_253735.JPG","locality": "Supertech Shopprix Mall","areaName": "Sector 61","costForTwo": "₹400 for two","cuisines": ["American"],"avgRating": 4.6,"parentId": "630","avgRatingString": "4.6","totalRatingsString": "27K+","sla": {"deliveryTime": 15,"lastMileTravel": 0.8,"serviceability": "SERVICEABLE","slaString": "10-15 mins","lastMileTravelString": "0.8 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-26 23:45:00","opened": true},"badges": {"imageBadges": [{"imageId": "android/static-assets/icons/big_rx.png","description": "bolt!"},{"imageId": "Ratnesh_Badges/Rx_Awards_2025/Bolt.png","description": "Delivery!"}]},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {"badgeObject": [{"attributes": {"description": "bolt!","imageId": "android/static-assets/icons/big_rx.png"}},{"attributes": {"description": "Delivery!","imageId": "Ratnesh_Badges/Rx_Awards_2025/Bolt.png"}}]},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹117"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}},
      {
"info": {
   "id": "485420","name": "KFC","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7dbdd987-b0fd-4182-ba39-9232c39faa6f_485420.JPG","locality": "H Block","areaName": "Sector 63","costForTwo": "₹400 for two","cuisines": ["Burgers","Fast Food","Rolls & Wraps"],"avgRating": 4.2,"parentId": "547","avgRatingString": "4.2","totalRatingsString": "6.1K+","sla": {"deliveryTime": 25,"lastMileTravel": 4.3,"serviceability": "SERVICEABLE","slaString": "25-30 mins","lastMileTravelString": "4.3 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-27 04:00:00","opened": true},"badges": {},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹79"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}},
   {
      "info":{"id": "24159","name": "Domino's Pizza","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/11/771a0b73-12d7-44c2-b6d3-c7db3d56e734_24159.JPG","locality": "Supertech Shoprix","areaName": "Sector 61","costForTwo": "₹400 for two","cuisines": ["Pizzas","Italian","Pastas","Desserts"],"avgRating": 4.4,"parentId": "2456","avgRatingString": "4.4","totalRatingsString": "8.2K+","sla": {"deliveryTime": 25,"lastMileTravel": 0.8,"serviceability": "SERVICEABLE","slaString": "20-25 mins","lastMileTravelString": "0.8 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-26 23:59:00","opened": true},"badges": {"imageBadges": [{"imageId": "android/static-assets/icons/big_rx.png","description": "bolt!"},{"imageId": "Ratnesh_Badges/Rx_Awards_2025/Bolt.png","description": "Delivery!"}]},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {"badgeObject": [{"attributes": {"description": "bolt!","imageId": "android/static-assets/icons/big_rx.png"}},{"attributes": {"description": "Delivery!","imageId": "Ratnesh_Badges/Rx_Awards_2025/Bolt.png"}}]},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹59"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}},
         {
         "info":{
            "id": "45512","name": "Theobroma","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/27/cde779ed-6e96-45a7-8ba0-e45f66c87318_45512.JPG","locality": "Morna","areaName": "Morna","costForTwo": "₹400 for two","cuisines": ["Bakery","Desserts"],"avgRating": 4.6,"parentId": "1040","avgRatingString": "4.6","totalRatingsString": "16K+","sla": {"deliveryTime": 20,"lastMileTravel": 3.7,"serviceability": "SERVICEABLE","slaString": "20-25 mins","lastMileTravelString": "3.7 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-28 02:00:00","opened": true},"badges": {"imageBadges": [{"imageId": "Rxawards/_CATEGORY-Desserts.png","description": "Delivery!"},{"imageId": "newg.png","description": "Gourmet"}]},"isOpen": true,"aggregatedDiscountInfoV2": {},"type": "F","badgesV2": {"entityBadges": {"imageBased": {"badgeObject": [{"attributes": {"description": "Delivery!","imageId": "Rxawards/_CATEGORY-Desserts.png"}},{"attributes": {"description": "Gourmet","imageId": "newg.png"}}]},"textBased": {},"textExtendedBadges": {}}},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "3.8","ratingCount": "11"},"source": "GOOGLE","sourceIconImageId": "v1704440323/google_ratings/rating_google_tag"},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
         }
               },
               {
         "info":{"id": "90872","name": "Burger King","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ae22cdf6-e866-43ef-a8ff-7da62c3d6f16_90872.jpg","locality": "North Eye","areaName": "Sector 74","costForTwo": "₹350 for two","cuisines": ["Burgers","American"],"avgRating": 4.3,"parentId": "166","avgRatingString": "4.3","totalRatingsString": "43K+","sla": {"deliveryTime": 37,"lastMileTravel": 6.8,"serviceability": "SERVICEABLE","slaString": "35-40 mins","lastMileTravelString": "6.8 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-28 05:00:00","opened": true},"badges": {"imageBadges": [{"imageId": "Rxawards/_CATEGORY-Burger.png","description": "Delivery!"}]},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {"badgeObject": [{"attributes": {"description": "Delivery!","imageId": "Rxawards/_CATEGORY-Burger.png"}}]},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹19"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}
               },
               {
                  "info":{"id": "359762","name": "BOX8 - Desi Meals","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/26/c23649f9-836a-461b-b63d-36a2ce26c9b0_359762.jpg","locality": "Mamura","areaName": "Sector 60","costForTwo": "₹200 for two","cuisines": ["North Indian","Biryani","Thalis","Home Food"],"avgRating": 4.5,"parentId": "10655","avgRatingString": "4.5","totalRatingsString": "6.3K+","sla": {"deliveryTime": 25,"lastMileTravel": 1.4,"serviceability": "SERVICEABLE","slaString": "20-30 mins","lastMileTravelString": "1.4 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-28 02:00:00","opened": true},"badges": {"imageBadges": [{"imageId": "android/static-assets/icons/big_rx.png","description": "bolt!"},{"imageId": "Rxawards/_CATEGORY-Butter%20Chicken.png","description": "Delivery!"}]},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {"badgeObject": [{"attributes": {"description": "bolt!","imageId": "android/static-assets/icons/big_rx.png"}},{"attributes": {"description": "Delivery!","imageId": "Rxawards/_CATEGORY-Butter%20Chicken.png"}}]},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹99"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}
               },
               {
                  "info":{"id": "391100","name": "ZAZA Mughal Biryani","cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2024/9/17/fdb2782d-035e-4cc3-b7fa-b54252036b19_391100.jpg","locality": "Mamura","areaName": "Sector 60","costForTwo": "₹250 for two","cuisines": ["Biryani","North Indian","Awadhi"],"avgRating": 4.5,"parentId": "22473","avgRatingString": "4.5","totalRatingsString": "1.3K+","sla": {"deliveryTime": 15,"lastMileTravel": 1.4,"serviceability": "SERVICEABLE","slaString": "10-20 mins","lastMileTravelString": "1.4 km","iconType": "ICON_TYPE_EMPTY"},"availability": {"nextCloseTime": "2025-11-28 02:00:00","opened": true},"badges": {"imageBadges": [{"imageId": "android/static-assets/icons/big_rx.png","description": "bolt!"},{"imageId": "Rxawards/_CATEGORY-Biryani.png","description": "Delivery!"}]},"isOpen": true,"type": "F","badgesV2": {"entityBadges": {"imageBased": {"badgeObject": [{"attributes": {"description": "bolt!","imageId": "android/static-assets/icons/big_rx.png"}},{"attributes": {"description": "Delivery!","imageId": "Rxawards/_CATEGORY-Biryani.png"}}]},"textBased": {},"textExtendedBadges": {}}},"aggregatedDiscountInfoV3": {"header": "ITEMS","subHeader": "AT ₹99"},"differentiatedUi": {"displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails": {"lottie": {},"video": {}}},"reviewsSummary": {},"displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo": {},"externalRatings": {"aggregatedRating": {"rating": "--"}},"ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"}
               }

]
export default resList